CREATE DATABASE Library
CREATE TABLE Library(
age INT NOT NULL,
name NVARCHAR NOT NULL,
isHuman BOOLEAN NOT NULL,)

CREATE TABLE Book(
name NVARCHAR NOT NULL,
author NVARCHAR NOT NULL,
pagesCount INT NOT NULL,
genre NVARCHAR NOT NULL,)

CREATE TABLE Car(
name NVARCHAR NOT NULL,
model NVARCHAR NOT NULL,
color NVARCHAR NOT NULL,
manufacturer NVARCHAR NOT NULL,)

CREATE TABLE TestClass(
id INT IDENTITY NOT NULL PRIMARY KEY,
mark DOUBLE NOT NULL,)

CREATE TABLE worker(
Id INT IDENTITY NOT NULL PRIMARY KEY,
name NVARCHAR NOT NULL,
work NVARCHAR NOT NULL,
salary DOUBLE NOT NULL,)
